#!/usr/bin/env bash
#comment
while read -r line
do
	username=$(echo "$line" | cut -d ":" -f1)
	uid=$(echo "$line" | cut -d ":" -f3 )
	home_dir=$(echo "$line" | cut -d ":" -f6 )
	echo "$username:$uid:$home_dir"
done < /etc/passwd
