#!/usr/bin/env bash
# Script creates a PID file and runs forever

file="/var/run/myscript.pid"

# /var/run icazə problemi üçün: əvvəl faylı YARAT
( umask 000; : > "$file" )

# PID yaz
echo "$$" > "$file"

# Traps
trap 'echo "I hate the kill command"; rm -f "$file"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'rm -f "$file"; exit' SIGQUIT

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done

